[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://express-production-f02d.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/templates/*"
  to = "https://express-production-f02d.up.railway.app/templates/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200