# Railway configuration for Express.js Presto Backend

[build]
# Use the standard Dockerfile for Node.js
dockerfilePath = "Dockerfile"

[deploy]
# Service configuration for Express server
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Health check configuration
healthcheckPath = "/api/health"
healthcheckTimeout = 30

# Resource configuration
[deploy.resources]
memory = "1Gi"
cpu = "500m"

# Environment variables
[env]
NODE_ENV = "production"
PORT = "3004"

# Networking
[networking]
# Expose Express server port
ports = [3004]