# Optimized Railway configuration for vLLM Llama 3.1
# Based on vLLM performance tuning best practices

[build]
# Use the optimized vLLM Dockerfile
dockerfilePath = "Dockerfile.vllm-optimized"

[deploy]
# Optimized service configuration
startCommand = "/start-vllm-optimized.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Health check configuration with longer timeout for model loading
healthcheckPath = "/health"
healthcheckTimeout = 180

# Optimized resource configuration for Llama 3.1 8B
[deploy.resources]
# Maximum memory allocation for better KV cache
memory = "16Gi"  # Increased from 8Gi for better performance
cpu = "8000m"    # Increased CPU allocation

# Optimized environment variables for maximum performance
[env]
# Model configuration
MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B-Instruct"
HOST = "0.0.0.0"
PORT = "8000"

# Hugging Face token (set this in Railway dashboard)
# HUGGING_FACE_HUB_TOKEN = "your-hf-token-here"

# vLLM Performance Optimizations
VLLM_WORKER_USE_RAY = "false"
VLLM_ATTENTION_BACKEND = "FLASHINFER"
VLLM_TENSOR_PARALLEL_SIZE = "1"

# Memory and batch optimizations
VLLM_GPU_MEMORY_UTILIZATION = "0.95"
VLLM_MAX_NUM_BATCHED_TOKENS = "16384"
VLLM_MAX_NUM_SEQS = "512"

# Scheduler optimizations
VLLM_NUM_SCHEDULER_STEPS = "12"
VLLM_MAX_SEQ_LEN_TO_CAPTURE = "16384"

# Disable features that may hurt performance
VLLM_ENABLE_CHUNKED_PREFILL = "false"
VLLM_ENABLE_PREFIX_CACHING = "false"

# System optimizations
VLLM_DISABLE_NUMA_BALANCING = "true"
NCCL_MIN_NCHANNELS = "4"

# Logging optimization
VLLM_DISABLE_LOG_REQUESTS = "true"

# CUDA optimizations
CUDA_VISIBLE_DEVICES = "0"
CUDA_LAUNCH_BLOCKING = "0"

# Python optimizations
PYTHONUNBUFFERED = "1"
PYTHONOPTIMIZE = "1"

# Networking configuration
[networking]
# Expose vLLM API port
ports = [8000]

# Volume for model caching with optimized path
[volumes]
# Cache models to avoid re-downloading
models = "/opt/models"
cache = "/opt/cache"

# Railway-specific optimizations
[build.env]
# Build-time optimizations
DOCKER_BUILDKIT = "1"
BUILDKIT_PROGRESS = "plain"

# Health check configuration
[healthcheck]
path = "/health"
timeout = 180
interval = 30
retries = 5