const fetch = require('node-fetch');

async function testPPTXGeneration() {
    const testData = {
        title: "Test Presentation",
        subtitle: "Generated by Presto Slides",
        slides: [
            {
                title: "Introduction",
                content: "Welcome to our test presentation. This slide demonstrates the basic content layout."
            },
            {
                title: "Key Features",
                type: "bullets",
                bullets: [
                    "AI-powered presentation generation",
                    "Professional color schemes",
                    "Automatic content fitting",
                    "Easy-to-use interface"
                ]
            },
            {
                title: "Conclusion",
                content: "Thank you for testing Presto Slides! This tool makes it easy to create professional PowerPoint presentations using AI."
            }
        ],
        colorScheme: "professional"
    };

    try {
        console.log('Testing PPTX generation...');
        
        const response = await fetch('http://localhost:3001/generate-pptx', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(testData)
        });

        if (response.ok) {
            console.log('✅ PPTX generation successful!');
            console.log('Response headers:', response.headers.get('content-type'));
            console.log('Content length:', response.headers.get('content-length'));
        } else {
            const error = await response.text();
            console.log('❌ PPTX generation failed:', error);
        }
    } catch (error) {
        console.log('❌ Test failed:', error.message);
    }
}

testPPTXGeneration();
