import React, { useMemo } from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
  Sequence,
  staticFile,
} from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { clockWipe } from "@remotion/transitions/clock-wipe";

// 1. Dynamic Data Example
const DATA_PROPS = {
  headline: "BREAKING NEWS",
  subheadline: "Remotion handles dynamic data seamlessly!",
  reporter: "Feedeo Agent",
};

// 2. Subtitle Example (Dummy synced data for our 5-second sine wave)
// Typically, you would load this from a JSON file generated by Whisper
const SUBTITLES = [
  { startFrame: 0, endFrame: 30, text: "This is..." },
  { startFrame: 30, endFrame: 60, text: "an audio-synced..." },
  { startFrame: 60, endFrame: 150, text: "subtitle demonstration." },
];

const DynamicNewsScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Spring animation for the text sliding in
  const slideIn = spring({
    frame,
    fps,
    config: { damping: 12 },
  });

  const translateY = interpolate(slideIn, [0, 1], [200, 0]);
  const opacity = interpolate(slideIn, [0, 1], [0, 1]);

  return (
    <AbsoluteFill style={{ backgroundColor: "#1e3a8a", justifyContent: "center", alignItems: "center" }}>
      <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", transform: `translateY(${translateY}px)`, opacity }}>
        <h1 style={{ color: "white", fontSize: 120, fontFamily: "sans-serif", fontWeight: "bold", margin: 0, textShadow: "0 10px 20px rgba(0,0,0,0.5)" }}>
          {DATA_PROPS.headline}
        </h1>
        <h2 style={{ color: "#fbbf24", fontSize: 60, fontFamily: "sans-serif", margin: "20px 0" }}>
          {DATA_PROPS.subheadline}
        </h2>
        <div style={{ backgroundColor: "white", color: "#1e3a8a", padding: "10px 40px", borderRadius: 50, fontSize: 40, fontFamily: "sans-serif", fontWeight: "bold", marginTop: 40 }}>
          Reporting: {DATA_PROPS.reporter}
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const SubtitleScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  // Find the active subtitle based on the current frame
  const activeSubtitle = SUBTITLES.find(
    (sub) => frame >= sub.startFrame && frame < sub.endFrame
  );

  return (
    <AbsoluteFill style={{ backgroundColor: "#065f46" }}>
      <Audio src={staticFile("voiceover.m4a")} />
      
      {/* Background visualizer (simulated using frames) */}
      <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity: 0.1 }}>
        <div
          style={{
            width: 400 + Math.sin(frame / 5) * 200,
            height: 400 + Math.cos(frame / 5) * 200,
            backgroundColor: "white",
            borderRadius: "50%",
          }}
        />
      </AbsoluteFill>

      {/* Subtitles */}
      <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 100 }}>
        {activeSubtitle ? (
          <div
            style={{
              backgroundColor: "rgba(0,0,0,0.8)",
              color: "white",
              padding: "20px 60px",
              borderRadius: 20,
              fontSize: 80,
              fontFamily: "monospace",
              textAlign: "center",
              border: "4px solid #10b981",
              textShadow: "0 4px 10px rgba(0,0,0,0.5)"
            }}
          >
            {activeSubtitle.text}
          </div>
        ) : null}
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

export const AdvancedDemo: React.FC = () => {
  return (
    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={90}>
        <DynamicNewsScene />
      </TransitionSeries.Sequence>
      
      <TransitionSeries.Transition
        presentation={clockWipe({ width: 1920, height: 1080 })}
        timing={linearTiming({ durationInFrames: 30 })}
      />
      
      <TransitionSeries.Sequence durationInFrames={150}>
        <SubtitleScene />
      </TransitionSeries.Sequence>
    </TransitionSeries>
  );
};
